// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
#ifndef INCLUDED_869a921fcf5bba54
#define INCLUDED_869a921fcf5bba54
#include "maglev/MagLevAny.h"
#endif
#ifndef INCLUDED_20db69a30a45e926
#define INCLUDED_20db69a30a45e926
#include "maglev/MagLevArray.h"
#endif
#ifndef INCLUDED_35ec03520fbb0747
#define INCLUDED_35ec03520fbb0747
#include "maglev/MagLevBoolean.h"
#endif
#ifndef INCLUDED_d8a74f90a5c0b964
#define INCLUDED_d8a74f90a5c0b964
#include "maglev/MagLevError.h"
#endif
#ifndef INCLUDED_ba46386e6aba7150
#define INCLUDED_ba46386e6aba7150
#include "maglev/MagLevNull.h"
#endif
#ifndef INCLUDED_95fa5e9194badcf5
#define INCLUDED_95fa5e9194badcf5
#include "maglev/MagLevNumber.h"
#endif
#ifndef INCLUDED_f4da16f85a617f60
#define INCLUDED_f4da16f85a617f60
#include "maglev/MagLevObject.h"
#endif
#ifndef INCLUDED_65acb6100057af6e
#define INCLUDED_65acb6100057af6e
#include "maglev/MagLevResult.h"
#endif
#ifndef INCLUDED_c859d2752ef86c43
#define INCLUDED_c859d2752ef86c43
#include "maglev/MagLevString.h"
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_englishauction_AuctionModel
#include <englishauction/AuctionModel.h>
#endif
#ifndef INCLUDED_englishauction_AuctionRepository
#include <englishauction/AuctionRepository.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_2c69b47eb41d373d_10_new,"englishauction.AuctionRepository","new",0x52210764,"englishauction.AuctionRepository.new","englishauction/AuctionRepository.hx",10,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_23_Add,"englishauction.AuctionRepository","Add",0x51fee105,"englishauction.AuctionRepository.Add","englishauction/AuctionRepository.hx",23,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_28_Add,"englishauction.AuctionRepository","Add",0x51fee105,"englishauction.AuctionRepository.Add","englishauction/AuctionRepository.hx",28,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_13_Add,"englishauction.AuctionRepository","Add",0x51fee105,"englishauction.AuctionRepository.Add","englishauction/AuctionRepository.hx",13,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_32_Edit,"englishauction.AuctionRepository","Edit",0x6faae2a6,"englishauction.AuctionRepository.Edit","englishauction/AuctionRepository.hx",32,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_36_Remove,"englishauction.AuctionRepository","Remove",0xa2d113e0,"englishauction.AuctionRepository.Remove","englishauction/AuctionRepository.hx",36,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_45_FindById,"englishauction.AuctionRepository","FindById",0xaec19d07,"englishauction.AuctionRepository.FindById","englishauction/AuctionRepository.hx",45,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_47_FindById,"englishauction.AuctionRepository","FindById",0xaec19d07,"englishauction.AuctionRepository.FindById","englishauction/AuctionRepository.hx",47,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_40_FindById,"englishauction.AuctionRepository","FindById",0xaec19d07,"englishauction.AuctionRepository.FindById","englishauction/AuctionRepository.hx",40,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_75_FindAuctionsEnding,"englishauction.AuctionRepository","FindAuctionsEnding",0x9fab848c,"englishauction.AuctionRepository.FindAuctionsEnding","englishauction/AuctionRepository.hx",75,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_77_FindAuctionsEnding,"englishauction.AuctionRepository","FindAuctionsEnding",0x9fab848c,"englishauction.AuctionRepository.FindAuctionsEnding","englishauction/AuctionRepository.hx",77,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_64_FindAuctionsEnding,"englishauction.AuctionRepository","FindAuctionsEnding",0x9fab848c,"englishauction.AuctionRepository.FindAuctionsEnding","englishauction/AuctionRepository.hx",64,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_109_FindAuctionsStarting,"englishauction.AuctionRepository","FindAuctionsStarting",0x9ec415a5,"englishauction.AuctionRepository.FindAuctionsStarting","englishauction/AuctionRepository.hx",109,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_111_FindAuctionsStarting,"englishauction.AuctionRepository","FindAuctionsStarting",0x9ec415a5,"englishauction.AuctionRepository.FindAuctionsStarting","englishauction/AuctionRepository.hx",111,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_98_FindAuctionsStarting,"englishauction.AuctionRepository","FindAuctionsStarting",0x9ec415a5,"englishauction.AuctionRepository.FindAuctionsStarting","englishauction/AuctionRepository.hx",98,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_140_FindOpenAuctions,"englishauction.AuctionRepository","FindOpenAuctions",0xeae4c32f,"englishauction.AuctionRepository.FindOpenAuctions","englishauction/AuctionRepository.hx",140,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_142_FindOpenAuctions,"englishauction.AuctionRepository","FindOpenAuctions",0xeae4c32f,"englishauction.AuctionRepository.FindOpenAuctions","englishauction/AuctionRepository.hx",142,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_131_FindOpenAuctions,"englishauction.AuctionRepository","FindOpenAuctions",0xeae4c32f,"englishauction.AuctionRepository.FindOpenAuctions","englishauction/AuctionRepository.hx",131,0xd2c1570d)
namespace englishauction{

void AuctionRepository_obj::__construct( ::maglev::MagLev bus){
            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_10_new)
HXDLIN(  10)		this->bus = bus;
            	}

Dynamic AuctionRepository_obj::__CreateEmpty() { return new AuctionRepository_obj; }

void *AuctionRepository_obj::_hx_vtable = 0;

Dynamic AuctionRepository_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< AuctionRepository_obj > _hx_result = new AuctionRepository_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool AuctionRepository_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x5dbb38da;
}

void AuctionRepository_obj::Add( ::englishauction::AuctionModel auction, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S1(::hx::LocalFunc,_hx_Closure_0, ::Dynamic,callback) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny ret){
            			HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_23_Add)
HXLINE(  24)			 ::Dynamic callback1 = callback;
HXDLIN(  24)			callback1(::hx::TCast<  ::maglev::MagLevString >::cast(ret)->getString());
HXLINE(  25)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_1) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError err){
            			HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_28_Add)
HXLINE(  28)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(err->getMessage()));
HXDLIN(  28)			return null();
            		}
            		HX_END_LOCAL_FUNC1(return)

            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_13_Add)
HXLINE(  14)		 ::maglev::MagLevObject obj = ::maglev::MagLevObject_obj::create();
HXLINE(  15)		obj->set(HX_("start",62,74,0b,84),::maglev::MagLevNumber_obj::fromInt(auction->start));
HXLINE(  16)		obj->set(HX_("end",db,03,4d,00),::maglev::MagLevNumber_obj::fromInt(auction->end));
HXLINE(  17)		obj->set(HX_("startingPrice",a9,64,6e,09),::maglev::MagLevNumber_obj::fromFloat(auction->startingPrice));
HXLINE(  18)		obj->set(HX_("reservePrice",ad,26,d1,1a),::maglev::MagLevNumber_obj::fromFloat(auction->reservePrice));
HXLINE(  19)		obj->set(HX_("priceIncrement",66,fe,46,ba),::maglev::MagLevNumber_obj::fromFloat(auction->priceIncrement));
HXLINE(  20)		 ::maglev::MagLevArray args = ::maglev::MagLevArray_obj::create();
HXLINE(  21)		args->push(obj);
HXLINE(  22)		 ::maglev::MagLevResult res = this->bus->call(HX_("Persistence.EnglishAuction.Auction.CreateNew",8d,d2,85,a5),args);
HXLINE(  23)		res->onResult( ::Dynamic(new _hx_Closure_0(callback)));
HXLINE(  27)		res->onError( ::Dynamic(new _hx_Closure_1()));
            	}


HX_DEFINE_DYNAMIC_FUNC2(AuctionRepository_obj,Add,(void))

void AuctionRepository_obj::Edit( ::englishauction::AuctionModel auction, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_32_Edit)
            	}


HX_DEFINE_DYNAMIC_FUNC2(AuctionRepository_obj,Edit,(void))

void AuctionRepository_obj::Remove(::String auctionId, ::Dynamic callback){
            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_36_Remove)
            	}


HX_DEFINE_DYNAMIC_FUNC2(AuctionRepository_obj,Remove,(void))

void AuctionRepository_obj::FindById(::String auctionId, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError err){
            			HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_45_FindById)
HXLINE(  45)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(err->getMessage()));
HXDLIN(  45)			return null();
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_1, ::maglev::MagLevResult,res, ::Dynamic,callback) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny ret){
            			HX_GC_STACKFRAME(&_hx_pos_2c69b47eb41d373d_47_FindById)
HXLINE(  48)			if (::Std_obj::isOfType(res->getResult(),( ( ::Dynamic)(::hx::ClassOf< ::maglev::MagLevNull >()) ))) {
HXLINE(  49)				callback(null());
            			}
HXLINE(  51)			 ::maglev::MagLevObject resobj = ::hx::TCast<  ::maglev::MagLevObject >::cast(res->getResult());
HXLINE(  52)			 ::englishauction::AuctionModel model =  ::englishauction::AuctionModel_obj::__alloc( HX_CTX );
HXLINE(  53)			model->id = ::hx::TCast<  ::maglev::MagLevString >::cast(resobj->get(HX_("auctionId",fe,08,7f,46)))->getString();
HXLINE(  54)			model->start = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("start",62,74,0b,84)))->getInt();
HXLINE(  55)			model->end = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("end",db,03,4d,00)))->getInt();
HXLINE(  56)			model->startingPrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("startingPrice",a9,64,6e,09)))->getFloat();
HXLINE(  57)			model->reservePrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("reservePrice",ad,26,d1,1a)))->getFloat();
HXLINE(  58)			model->priceIncrement = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("priceIncrement",66,fe,46,ba)))->getFloat();
HXLINE(  59)			callback(model);
HXLINE(  60)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            		}
            		HX_END_LOCAL_FUNC1(return)

            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_40_FindById)
HXLINE(  41)		 ::maglev::MagLevArray args = ::maglev::MagLevArray_obj::create();
HXLINE(  42)		args->push(::maglev::MagLevString_obj::fromString(auctionId));
HXLINE(  43)		 ::maglev::MagLevResult res = this->bus->call(HX_("Persistence.EnglishAuction.Auction.FindById",c2,26,2f,01),args);
HXLINE(  44)		res->onError( ::Dynamic(new _hx_Closure_0()));
HXLINE(  47)		res->onResult( ::Dynamic(new _hx_Closure_1(res,callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC2(AuctionRepository_obj,FindById,(void))

void AuctionRepository_obj::FindAuctionsEnding(int endfrom,int endto,int page,int perpage,::String sort,bool asc, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError err){
            			HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_75_FindAuctionsEnding)
HXLINE(  75)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(err->getMessage()));
HXDLIN(  75)			return null();
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_1,::Array< ::Dynamic>,auctions, ::Dynamic,callback) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny ret){
            			HX_GC_STACKFRAME(&_hx_pos_2c69b47eb41d373d_77_FindAuctionsEnding)
HXLINE(  78)			 ::maglev::MagLevArray arr = ::hx::TCast<  ::maglev::MagLevArray >::cast(ret);
HXLINE(  79)			int i = 0;
HXLINE(  80)			while((i < arr->size())){
HXLINE(  81)				 ::englishauction::AuctionModel model =  ::englishauction::AuctionModel_obj::__alloc( HX_CTX );
HXLINE(  82)				 ::maglev::MagLevObject resobj = ::hx::TCast<  ::maglev::MagLevObject >::cast(arr->get(i));
HXLINE(  83)				model->id = ::hx::TCast<  ::maglev::MagLevString >::cast(resobj->get(HX_("auctionId",fe,08,7f,46)))->getString();
HXLINE(  84)				model->start = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("start",62,74,0b,84)))->getInt();
HXLINE(  85)				model->end = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("end",db,03,4d,00)))->getInt();
HXLINE(  86)				model->startingPrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("startingPrice",a9,64,6e,09)))->getFloat();
HXLINE(  87)				model->reservePrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("reservePrice",ad,26,d1,1a)))->getFloat();
HXLINE(  88)				model->priceIncrement = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("priceIncrement",66,fe,46,ba)))->getFloat();
HXLINE(  89)				auctions->push(model);
HXLINE(  90)				i = (i + 1);
            			}
HXLINE(  92)			callback(auctions);
HXLINE(  93)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            		}
            		HX_END_LOCAL_FUNC1(return)

            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_64_FindAuctionsEnding)
HXLINE(  65)		::Array< ::Dynamic> auctions = ::Array_obj< ::Dynamic>::__new();
HXLINE(  66)		 ::maglev::MagLevArray args = ::maglev::MagLevArray_obj::create();
HXLINE(  67)		args->push(::maglev::MagLevNumber_obj::fromInt(endfrom));
HXLINE(  68)		args->push(::maglev::MagLevNumber_obj::fromInt(endto));
HXLINE(  69)		args->push(::maglev::MagLevNumber_obj::fromInt(page));
HXLINE(  70)		args->push(::maglev::MagLevNumber_obj::fromInt(perpage));
HXLINE(  71)		args->push(::maglev::MagLevString_obj::fromString(sort));
HXLINE(  72)		args->push(::maglev::MagLevBoolean_obj::fromBool(asc));
HXLINE(  73)		 ::maglev::MagLevResult res = this->bus->call(HX_("Persistence.EnglishAuction.Auction.FindEnding",17,7d,de,f7),args);
HXLINE(  74)		res->onError( ::Dynamic(new _hx_Closure_0()));
HXLINE(  77)		res->onResult( ::Dynamic(new _hx_Closure_1(auctions,callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC7(AuctionRepository_obj,FindAuctionsEnding,(void))

void AuctionRepository_obj::FindAuctionsStarting(int startfrom,int startto,int page,int perpage,::String sort,bool asc, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError err){
            			HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_109_FindAuctionsStarting)
HXLINE( 109)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(err->getMessage()));
HXDLIN( 109)			return null();
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S3(::hx::LocalFunc,_hx_Closure_1,::Array< ::Dynamic>,auctions, ::maglev::MagLevResult,res, ::Dynamic,callback) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny ret){
            			HX_GC_STACKFRAME(&_hx_pos_2c69b47eb41d373d_111_FindAuctionsStarting)
HXLINE( 112)			 ::maglev::MagLevArray arr = ::hx::TCast<  ::maglev::MagLevArray >::cast(res->getResult());
HXLINE( 113)			int i = 0;
HXLINE( 114)			while((i < arr->size())){
HXLINE( 115)				 ::englishauction::AuctionModel model =  ::englishauction::AuctionModel_obj::__alloc( HX_CTX );
HXLINE( 116)				 ::maglev::MagLevObject resobj = ::hx::TCast<  ::maglev::MagLevObject >::cast(arr->get(i));
HXLINE( 117)				model->id = ::hx::TCast<  ::maglev::MagLevString >::cast(resobj->get(HX_("auctionId",fe,08,7f,46)))->getString();
HXLINE( 118)				model->start = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("start",62,74,0b,84)))->getInt();
HXLINE( 119)				model->end = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("end",db,03,4d,00)))->getInt();
HXLINE( 120)				model->startingPrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("startingPrice",a9,64,6e,09)))->getFloat();
HXLINE( 121)				model->reservePrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("reservePrice",ad,26,d1,1a)))->getFloat();
HXLINE( 122)				model->priceIncrement = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("priceIncrement",66,fe,46,ba)))->getFloat();
HXLINE( 123)				auctions->push(model);
HXLINE( 124)				i = (i + 1);
            			}
HXLINE( 126)			callback(auctions);
HXLINE( 127)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            		}
            		HX_END_LOCAL_FUNC1(return)

            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_98_FindAuctionsStarting)
HXLINE(  99)		::Array< ::Dynamic> auctions = ::Array_obj< ::Dynamic>::__new();
HXLINE( 100)		 ::maglev::MagLevArray args = ::maglev::MagLevArray_obj::create();
HXLINE( 101)		args->push(::maglev::MagLevNumber_obj::fromInt(startfrom));
HXLINE( 102)		args->push(::maglev::MagLevNumber_obj::fromInt(startto));
HXLINE( 103)		args->push(::maglev::MagLevNumber_obj::fromInt(page));
HXLINE( 104)		args->push(::maglev::MagLevNumber_obj::fromInt(perpage));
HXLINE( 105)		args->push(::maglev::MagLevString_obj::fromString(sort));
HXLINE( 106)		args->push(::maglev::MagLevBoolean_obj::fromBool(asc));
HXLINE( 107)		 ::maglev::MagLevResult res = this->bus->call(HX_("Persistence.EnglishAuction.Auction.FindStarting",f0,86,0e,a4),args);
HXLINE( 108)		res->onError( ::Dynamic(new _hx_Closure_0()));
HXLINE( 111)		res->onResult( ::Dynamic(new _hx_Closure_1(auctions,res,callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC7(AuctionRepository_obj,FindAuctionsStarting,(void))

void AuctionRepository_obj::FindOpenAuctions(int page,int perpage,::String sort,bool asc, ::Dynamic callback){
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevError err){
            			HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_140_FindOpenAuctions)
HXLINE( 140)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(err->getMessage()));
HXDLIN( 140)			return null();
            		}
            		HX_END_LOCAL_FUNC1(return)

            		HX_BEGIN_LOCAL_FUNC_S3(::hx::LocalFunc,_hx_Closure_1,::Array< ::Dynamic>,auctions, ::maglev::MagLevResult,res, ::Dynamic,callback) HXARGC(1)
            		 ::maglev::MagLevResult _hx_run( ::maglev::MagLevAny ret){
            			HX_GC_STACKFRAME(&_hx_pos_2c69b47eb41d373d_142_FindOpenAuctions)
HXLINE( 143)			 ::maglev::MagLevArray arr = ::hx::TCast<  ::maglev::MagLevArray >::cast(res->getResult());
HXLINE( 144)			int i = 0;
HXLINE( 145)			while((i < arr->size())){
HXLINE( 146)				 ::englishauction::AuctionModel model =  ::englishauction::AuctionModel_obj::__alloc( HX_CTX );
HXLINE( 147)				 ::maglev::MagLevObject resobj = ::hx::TCast<  ::maglev::MagLevObject >::cast(arr->get(i));
HXLINE( 148)				model->id = ::hx::TCast<  ::maglev::MagLevString >::cast(resobj->get(HX_("auctionId",fe,08,7f,46)))->getString();
HXLINE( 149)				model->start = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("start",62,74,0b,84)))->getInt();
HXLINE( 150)				model->end = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("end",db,03,4d,00)))->getInt();
HXLINE( 151)				model->startingPrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("startingPrice",a9,64,6e,09)))->getFloat();
HXLINE( 152)				model->reservePrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("reservePrice",ad,26,d1,1a)))->getFloat();
HXLINE( 153)				model->priceIncrement = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("priceIncrement",66,fe,46,ba)))->getFloat();
HXLINE( 154)				auctions->push(model);
HXLINE( 155)				i = (i + 1);
            			}
HXLINE( 157)			callback(auctions);
HXLINE( 158)			return ::maglev::MagLevResult_obj::fromResult(::maglev::MagLevNull_obj::create());
            		}
            		HX_END_LOCAL_FUNC1(return)

            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_131_FindOpenAuctions)
HXLINE( 132)		::Array< ::Dynamic> auctions = ::Array_obj< ::Dynamic>::__new();
HXLINE( 133)		 ::maglev::MagLevArray args = ::maglev::MagLevArray_obj::create();
HXLINE( 134)		args->push(::maglev::MagLevNumber_obj::fromInt(page));
HXLINE( 135)		args->push(::maglev::MagLevNumber_obj::fromInt(perpage));
HXLINE( 136)		args->push(::maglev::MagLevString_obj::fromString(sort));
HXLINE( 137)		args->push(::maglev::MagLevBoolean_obj::fromBool(asc));
HXLINE( 138)		 ::maglev::MagLevResult res = this->bus->call(HX_("Persistence.EnglishAuction.Auction.FindOpen",fa,30,c0,09),args);
HXLINE( 139)		res->onError( ::Dynamic(new _hx_Closure_0()));
HXLINE( 142)		res->onResult( ::Dynamic(new _hx_Closure_1(auctions,res,callback)));
            	}


HX_DEFINE_DYNAMIC_FUNC5(AuctionRepository_obj,FindOpenAuctions,(void))


::hx::ObjectPtr< AuctionRepository_obj > AuctionRepository_obj::__new( ::maglev::MagLev bus) {
	::hx::ObjectPtr< AuctionRepository_obj > __this = new AuctionRepository_obj();
	__this->__construct(bus);
	return __this;
}

::hx::ObjectPtr< AuctionRepository_obj > AuctionRepository_obj::__alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev bus) {
	AuctionRepository_obj *__this = (AuctionRepository_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(AuctionRepository_obj), true, "englishauction.AuctionRepository"));
	*(void **)__this = AuctionRepository_obj::_hx_vtable;
	__this->__construct(bus);
	return __this;
}

AuctionRepository_obj::AuctionRepository_obj()
{
}

void AuctionRepository_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(AuctionRepository);
	HX_MARK_MEMBER_NAME(bus,"bus");
	HX_MARK_END_CLASS();
}

void AuctionRepository_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(bus,"bus");
}

::hx::Val AuctionRepository_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"bus") ) { return ::hx::Val( bus ); }
		if (HX_FIELD_EQ(inName,"Add") ) { return ::hx::Val( Add_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"Edit") ) { return ::hx::Val( Edit_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"Remove") ) { return ::hx::Val( Remove_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"FindById") ) { return ::hx::Val( FindById_dyn() ); }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"FindOpenAuctions") ) { return ::hx::Val( FindOpenAuctions_dyn() ); }
		break;
	case 18:
		if (HX_FIELD_EQ(inName,"FindAuctionsEnding") ) { return ::hx::Val( FindAuctionsEnding_dyn() ); }
		break;
	case 20:
		if (HX_FIELD_EQ(inName,"FindAuctionsStarting") ) { return ::hx::Val( FindAuctionsStarting_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val AuctionRepository_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"bus") ) { bus=inValue.Cast<  ::maglev::MagLev >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void AuctionRepository_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("bus",40,c3,4a,00));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo AuctionRepository_obj_sMemberStorageInfo[] = {
	{::hx::fsUnknown /*  ::maglev::MagLev */ ,(int)offsetof(AuctionRepository_obj,bus),HX_("bus",40,c3,4a,00)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *AuctionRepository_obj_sStaticStorageInfo = 0;
#endif

static ::String AuctionRepository_obj_sMemberFields[] = {
	HX_("bus",40,c3,4a,00),
	HX_("Add",01,aa,31,00),
	HX_("Edit",2a,f6,e7,2d),
	HX_("Remove",64,10,1d,39),
	HX_("FindById",8b,c2,68,6d),
	HX_("FindAuctionsEnding",10,37,42,6d),
	HX_("FindAuctionsStarting",29,71,4f,05),
	HX_("FindOpenAuctions",b3,0c,33,d1),
	::String(null()) };

::hx::Class AuctionRepository_obj::__mClass;

void AuctionRepository_obj::__register()
{
	AuctionRepository_obj _hx_dummy;
	AuctionRepository_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("englishauction.AuctionRepository",72,c5,70,27);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(AuctionRepository_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< AuctionRepository_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = AuctionRepository_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = AuctionRepository_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace englishauction
