// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
#ifndef INCLUDED_869a921fcf5bba54
#define INCLUDED_869a921fcf5bba54
#include "maglev/MagLevAny.h"
#endif
#ifndef INCLUDED_20db69a30a45e926
#define INCLUDED_20db69a30a45e926
#include "maglev/MagLevArray.h"
#endif
#ifndef INCLUDED_d8a74f90a5c0b964
#define INCLUDED_d8a74f90a5c0b964
#include "maglev/MagLevError.h"
#endif
#ifndef INCLUDED_ba46386e6aba7150
#define INCLUDED_ba46386e6aba7150
#include "maglev/MagLevNull.h"
#endif
#ifndef INCLUDED_95fa5e9194badcf5
#define INCLUDED_95fa5e9194badcf5
#include "maglev/MagLevNumber.h"
#endif
#ifndef INCLUDED_f4da16f85a617f60
#define INCLUDED_f4da16f85a617f60
#include "maglev/MagLevObject.h"
#endif
#ifndef INCLUDED_65acb6100057af6e
#define INCLUDED_65acb6100057af6e
#include "maglev/MagLevResult.h"
#endif
#ifndef INCLUDED_c859d2752ef86c43
#define INCLUDED_c859d2752ef86c43
#include "maglev/MagLevString.h"
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_englishauction_AuctionModel
#include <englishauction/AuctionModel.h>
#endif
#ifndef INCLUDED_englishauction_AuctionRepository
#include <englishauction/AuctionRepository.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_2c69b47eb41d373d_10_new,"englishauction.AuctionRepository","new",0x52210764,"englishauction.AuctionRepository.new","englishauction/AuctionRepository.hx",10,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_13_Add,"englishauction.AuctionRepository","Add",0x51fee105,"englishauction.AuctionRepository.Add","englishauction/AuctionRepository.hx",13,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_17_Edit,"englishauction.AuctionRepository","Edit",0x6faae2a6,"englishauction.AuctionRepository.Edit","englishauction/AuctionRepository.hx",17,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_21_Remove,"englishauction.AuctionRepository","Remove",0xa2d113e0,"englishauction.AuctionRepository.Remove","englishauction/AuctionRepository.hx",21,0xd2c1570d)
HX_LOCAL_STACK_FRAME(_hx_pos_2c69b47eb41d373d_25_FindById,"englishauction.AuctionRepository","FindById",0xaec19d07,"englishauction.AuctionRepository.FindById","englishauction/AuctionRepository.hx",25,0xd2c1570d)
namespace englishauction{

void AuctionRepository_obj::__construct( ::maglev::MagLev bus){
            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_10_new)
HXDLIN(  10)		this->bus = bus;
            	}

Dynamic AuctionRepository_obj::__CreateEmpty() { return new AuctionRepository_obj; }

void *AuctionRepository_obj::_hx_vtable = 0;

Dynamic AuctionRepository_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< AuctionRepository_obj > _hx_result = new AuctionRepository_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool AuctionRepository_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x5dbb38da;
}

void AuctionRepository_obj::Add( ::englishauction::AuctionModel auction){
            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_13_Add)
            	}


HX_DEFINE_DYNAMIC_FUNC1(AuctionRepository_obj,Add,(void))

void AuctionRepository_obj::Edit( ::englishauction::AuctionModel auction){
            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_17_Edit)
            	}


HX_DEFINE_DYNAMIC_FUNC1(AuctionRepository_obj,Edit,(void))

void AuctionRepository_obj::Remove(::String auctionId){
            	HX_STACKFRAME(&_hx_pos_2c69b47eb41d373d_21_Remove)
            	}


HX_DEFINE_DYNAMIC_FUNC1(AuctionRepository_obj,Remove,(void))

 ::englishauction::AuctionModel AuctionRepository_obj::FindById(::String auctionId){
            	HX_GC_STACKFRAME(&_hx_pos_2c69b47eb41d373d_25_FindById)
HXLINE(  26)		 ::maglev::MagLevArray myargs = ::maglev::MagLevArray_obj::create();
HXLINE(  27)		myargs->push(::maglev::MagLevString_obj::fromString(HX_("EnglishAuction.Auction",c8,f3,cc,ba)));
HXLINE(  28)		myargs->push(::maglev::MagLevString_obj::fromString(HX_("FindById",8b,c2,68,6d)));
HXLINE(  29)		myargs->push(::maglev::MagLevString_obj::fromString(auctionId));
HXLINE(  30)		 ::maglev::MagLevResult res = this->bus->call(HX_("Persistence.Get",c7,c3,56,12),myargs);
HXLINE(  31)		if (res->isError()) {
HXLINE(  32)			HX_STACK_DO_THROW(::haxe::Exception_obj::thrown(res->getError()->getMessage()));
            		}
HXLINE(  34)		if (::Std_obj::isOfType(res->getResult(),( ( ::Dynamic)(::hx::ClassOf< ::maglev::MagLevNull >()) ))) {
HXLINE(  35)			return null();
            		}
HXLINE(  37)		 ::maglev::MagLevObject resobj = ::hx::TCast<  ::maglev::MagLevObject >::cast(res->getResult());
HXLINE(  38)		 ::englishauction::AuctionModel model =  ::englishauction::AuctionModel_obj::__alloc( HX_CTX );
HXLINE(  39)		model->id = ::hx::TCast<  ::maglev::MagLevString >::cast(resobj->get(HX_("auctionId",fe,08,7f,46)))->getString();
HXLINE(  40)		model->start = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("start",62,74,0b,84)))->getInt();
HXLINE(  41)		model->end = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("end",db,03,4d,00)))->getInt();
HXLINE(  42)		model->startingPrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("startingPrice",a9,64,6e,09)))->getFloat();
HXLINE(  43)		model->reservePrice = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("reservePrice",ad,26,d1,1a)))->getFloat();
HXLINE(  44)		model->priceIncrement = ::hx::TCast<  ::maglev::MagLevNumber >::cast(resobj->get(HX_("priceIncrement",66,fe,46,ba)))->getFloat();
HXLINE(  45)		return model;
            	}


HX_DEFINE_DYNAMIC_FUNC1(AuctionRepository_obj,FindById,return )


::hx::ObjectPtr< AuctionRepository_obj > AuctionRepository_obj::__new( ::maglev::MagLev bus) {
	::hx::ObjectPtr< AuctionRepository_obj > __this = new AuctionRepository_obj();
	__this->__construct(bus);
	return __this;
}

::hx::ObjectPtr< AuctionRepository_obj > AuctionRepository_obj::__alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev bus) {
	AuctionRepository_obj *__this = (AuctionRepository_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(AuctionRepository_obj), true, "englishauction.AuctionRepository"));
	*(void **)__this = AuctionRepository_obj::_hx_vtable;
	__this->__construct(bus);
	return __this;
}

AuctionRepository_obj::AuctionRepository_obj()
{
}

void AuctionRepository_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(AuctionRepository);
	HX_MARK_MEMBER_NAME(bus,"bus");
	HX_MARK_END_CLASS();
}

void AuctionRepository_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(bus,"bus");
}

::hx::Val AuctionRepository_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"bus") ) { return ::hx::Val( bus ); }
		if (HX_FIELD_EQ(inName,"Add") ) { return ::hx::Val( Add_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"Edit") ) { return ::hx::Val( Edit_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"Remove") ) { return ::hx::Val( Remove_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"FindById") ) { return ::hx::Val( FindById_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val AuctionRepository_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"bus") ) { bus=inValue.Cast<  ::maglev::MagLev >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void AuctionRepository_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("bus",40,c3,4a,00));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo AuctionRepository_obj_sMemberStorageInfo[] = {
	{::hx::fsUnknown /*  ::maglev::MagLev */ ,(int)offsetof(AuctionRepository_obj,bus),HX_("bus",40,c3,4a,00)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *AuctionRepository_obj_sStaticStorageInfo = 0;
#endif

static ::String AuctionRepository_obj_sMemberFields[] = {
	HX_("bus",40,c3,4a,00),
	HX_("Add",01,aa,31,00),
	HX_("Edit",2a,f6,e7,2d),
	HX_("Remove",64,10,1d,39),
	HX_("FindById",8b,c2,68,6d),
	::String(null()) };

::hx::Class AuctionRepository_obj::__mClass;

void AuctionRepository_obj::__register()
{
	AuctionRepository_obj _hx_dummy;
	AuctionRepository_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("englishauction.AuctionRepository",72,c5,70,27);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(AuctionRepository_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< AuctionRepository_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = AuctionRepository_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = AuctionRepository_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace englishauction
