// Generated by Haxe 4.1.1
#ifndef INCLUDED_englishauction_AuctionModel
#define INCLUDED_englishauction_AuctionModel

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_f9e3deea883a82ba_5_new)
HX_DECLARE_CLASS1(englishauction,AuctionModel)

namespace englishauction{


class HXCPP_CLASS_ATTRIBUTES AuctionModel_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef AuctionModel_obj OBJ_;
		AuctionModel_obj();

	public:
		enum { _hx_ClassId = 0x0621ba85 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="englishauction.AuctionModel")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"englishauction.AuctionModel"); }

		inline static ::hx::ObjectPtr< AuctionModel_obj > __new() {
			::hx::ObjectPtr< AuctionModel_obj > __this = new AuctionModel_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< AuctionModel_obj > __alloc(::hx::Ctx *_hx_ctx) {
			AuctionModel_obj *__this = (AuctionModel_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(AuctionModel_obj), true, "englishauction.AuctionModel"));
			*(void **)__this = AuctionModel_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_f9e3deea883a82ba_5_new)
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~AuctionModel_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("AuctionModel",86,5a,b8,a1); }

		::String id;
		int start;
		int end;
		Float startingPrice;
		Float reservePrice;
		Float priceIncrement;
};

} // end namespace englishauction

#endif /* INCLUDED_englishauction_AuctionModel */ 
