// Generated by Haxe 4.1.1
#ifndef INCLUDED_englishauction_BidModel
#define INCLUDED_englishauction_BidModel

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_c3f119f07bcfb584_5_new)
HX_DECLARE_CLASS1(englishauction,BidModel)

namespace englishauction{


class HXCPP_CLASS_ATTRIBUTES BidModel_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef BidModel_obj OBJ_;
		BidModel_obj();

	public:
		enum { _hx_ClassId = 0x2232b61f };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="englishauction.BidModel")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"englishauction.BidModel"); }

		inline static ::hx::ObjectPtr< BidModel_obj > __new() {
			::hx::ObjectPtr< BidModel_obj > __this = new BidModel_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< BidModel_obj > __alloc(::hx::Ctx *_hx_ctx) {
			BidModel_obj *__this = (BidModel_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(BidModel_obj), true, "englishauction.BidModel"));
			*(void **)__this = BidModel_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_c3f119f07bcfb584_5_new)
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~BidModel_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("BidModel",cc,c9,84,68); }

		::String id;
		::String auctionId;
		::String userId;
		Float amount;
};

} // end namespace englishauction

#endif /* INCLUDED_englishauction_BidModel */ 
